POST http://localhost:4001/api/tracks
Content-Type: application/json

{
  "name": "Oliveira dos cen anos",
  "artistId": "66269bac6169ed0632cbffb1",
  "url": "https://res.cloudinary.com/dmyqjn66d/video/upload/v1713955111/YE/Ghost_Town_-_Kanye_West_rsk0in.mp3",
  "thumbnail": "https://res.cloudinary.com/dmyqjn66d/image/upload/v1713635011/track-img/faaj1abhsr8iwxkgax6v.jpg",
  "genreName": "Rap",
  "albumId": "662a4760ab15446287810c00"
}


// C. Tangana 66269bac6169ed0632cbffb1
// Oliveira dos cen anos

// Nebulossa
// Zorra