POST http://localhost:4001/api/tracks
Content-Type: application/json

{
  "name": "Demasiadas mujeres",
  "artistName": "C. Tangana",
  "url": "https://ejemplo.com/cancion_prueba.mp3",
  "thumbnail": "https://ejemplo.com/thumbnail_prueba.jpg",
  "genreName": "Trap",
  "albumName": "El Madrileño"
}