POST http://localhost:4001/api/albums
Content-Type: application/json
Authorization: Bearer  
{
"name": "Oliveira dos cen anos",
"thumbnail": "https://res.cloudinary.com/dmyqjn66d/image/upload/v1714328201/track-img/ch8gdzxyuzbh8fy44kkn.png",
"genre": "trap",
"artist": "C. Tangana"
}
