POST http://localhost:3333/api/users
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "123456K*",
    "name": "manuel",
    "gender":"male",
    "birthDate":"2003-05-29",
    "country":"Spain"
}